### ISSUE TITLE
Staking always loading

### ISSUE THREAD

**Issue by osef123** [obsidianproject/CoreWallet#5]
I tried to restart the wallet, it's the same. It staked well 10h ago, i changed nothing.

[https://media.discordapp.net/attachments/587769867248336897/652400811573510165/Sans_titre.png](url)
![image](https://user-images.githubusercontent.com/3747761/70302772-2b12b600-17fe-11ea-9833-b5776d0a47a2.png)

**Comment by aubergemediale** [comment]
...and a restart didn't help either, right?

**Comment by osef123** [comment]
"I tried to restart the wallet, it's the same"

**Comment by thecrypt0hunter** [comment]
I am monitoring this issue, but I expect its because there are no mature coins to stake.

**Comment by thecrypt0hunter** [comment]
My coins matured and staking started as expected - maybe we just need a timeout and an error message rather than spinner going until the coins mature.

**Comment by dangershony** [comment]
I think it's just a reload issue, if you navigate to another tab and then back it appears to be fixed.

**Comment by osef123** [comment]
> I think it's just a reload issue, if you navigate to another tab and then back it appears to be fixed.

You are right ! :)

**Comment by osef123** [comment]
Fixed but not fully fixed:

![Sans titre](https://user-images.githubusercontent.com/3747761/70320845-05010c00-1826-11ea-9845-a27a52f81a9d.png)

**Comment by dangershony** [comment]
This PR by @zeptin should fix it
https://github.com/stratisproject/StratisBitcoinFullNode/commit/884dbae65c46a48db9da5a82d758eecf106f7584

I will try to import it to Obsidian

**Comment by thecrypt0hunter** [comment]
I have just tested this with release v1.0.1 and I was unable to recreate this issue.

**Comment by dangershony** [comment]
Thank you @thecrypt0hunter (closing)
